using System.Net;
using System.Text;
using CapstoneProject.Models;

namespace CapstoneProject.Services
{
    public class PageBuilderService
    {
        public GeneratedPage Build(ExtractionResult extractionResult)
        {
            extractionResult ??= new ExtractionResult();

            var appName = extractionResult.Fields
                .FirstOrDefault(f => IsField(f.Name, "Application Name", "App Name", "Name", "Service Name"))?
                .Value;

            if (string.IsNullOrWhiteSpace(appName) || appName == "Not Found")
            {
                appName = "Unknown Application";
            }

            var title = $"{appName} - Technical Profile (Auto-Generated)";
            var content = BuildConfluenceStorageContent(extractionResult);

            return new GeneratedPage
            {
                Title = title,
                Content = content,
                LastUpdated = DateTime.UtcNow
            };
        }

        private static string BuildConfluenceStorageContent(ExtractionResult extractionResult)
        {
            var sb = new StringBuilder();

            sb.AppendLine("<h1>Application Profile</h1>");
            sb.AppendLine("<p><strong>Generated By:</strong> EliteA Automated Sync</p>");
            sb.AppendLine($"<p><strong>Last Updated:</strong> {DateTime.UtcNow:yyyy-MM-dd}</p>");

            sb.AppendLine("<h2>Executive Summary</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "Application Name", GetFieldValue(extractionResult, "Application Name", "App Name", "Name", "Service Name"));
            AppendRow(sb, "Project Overview", GetFieldValue(extractionResult, "Project Overview", "Overview", "Description"));
            AppendRow(sb, "Service Owner", GetFieldValue(extractionResult, "Maintainers", "Owner", "Authors", "Service Owner"));
            AppendRow(sb, "Business Impact", "Not Found");
            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>System Architecture & Tech Stack</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "Language/Runtime", GetFieldValue(extractionResult, "System Architecture", "Tech Stack", "Architecture"));
            AppendRow(sb, "Frameworks", GetFieldValue(extractionResult, "System Architecture", "Tech Stack", "Architecture"));
            AppendRow(sb, "Primary Database", GetFieldValue(extractionResult, "Primary Database"));
            AppendRow(sb, "Cloud Provider", GetFieldValue(extractionResult, "Cloud Provider"));
            AppendRow(sb, "Infrastructure", GetFieldValue(extractionResult, "Infrastructure"));

            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>Integration & Dependencies</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "Upstream Dependencies", "Not Found");
            AppendRow(sb, "Downstream Consumers", "Not Found");
            AppendRow(sb, "External APIs", "Not Found");

            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>Technical Configuration</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "Main Branch", "main");
            AppendRow(sb, "Build Tool", GetFieldValue(extractionResult, "Build Tool"));
            AppendRow(sb, "Critical Env Variables", GetFieldValue(extractionResult, "Environment Config", "Env Config", "Critical Env Variables"));
            AppendRow(sb, "Deployment Pipeline", GetFieldValue(extractionResult, "Deployment Pipeline"));

            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>Quality & Compliance</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "Test Frameworks", GetFieldValue(extractionResult, "Test Frameworks"));
            AppendRow(sb, "Code Coverage Goal", "Not Found");
            AppendRow(sb, "Security Scanning", "Not Found");
            AppendRow(sb, "Observation/Logging", "Not Found");

            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>Documentation & Resources</h2>");
            sb.AppendLine("<table>");
            sb.AppendLine("<tbody>");

            AppendRow(sb, "GitHub Repository", "Not Found");
            AppendRow(sb, "API Documentation", "Not Found");
            AppendRow(sb, "JIRA Board", "Not Found");
            AppendRow(sb, "On-Call Rotation", "Not Found");

            sb.AppendLine("</tbody>");
            sb.AppendLine("</table>");

            sb.AppendLine("<h2>Deployment Status</h2>");
            sb.AppendLine("<p><strong>Current Version:</strong> Not Found</p>");
            sb.AppendLine($"<p><strong>Last Updated:</strong> {DateTime.UtcNow:yyyy-MM-dd} (via EliteA Automated Sync)</p>");

            return sb.ToString();
        }

        private static void AppendRow(StringBuilder sb, string label, string value)
        {
            sb.AppendLine("<tr>");
            sb.AppendLine($"<th>{WebUtility.HtmlEncode(label)}</th>");
            sb.AppendLine($"<td>{WebUtility.HtmlEncode(string.IsNullOrWhiteSpace(value) ? "Not Found" : value)}</td>");
            sb.AppendLine("</tr>");
        }

        private static string GetFieldValue(ExtractionResult extractionResult, params string[] names)
        {
            if (extractionResult?.Fields == null)
                return "Not Found";

            foreach (var name in names)
            {
                var field = extractionResult.Fields
                    .FirstOrDefault(f => IsField(f.Name, name));

                if (field != null && !string.IsNullOrWhiteSpace(field.Value))
                {
                    return field.Value;
                }
            }

            return "Not Found";
        }

        private static bool IsField(string? actual, params string[] expectedNames)
        {
            if (string.IsNullOrWhiteSpace(actual))
                return false;

            var normalizedActual = Normalize(actual);

            foreach (var expected in expectedNames)
            {
                if (normalizedActual == Normalize(expected))
                    return true;
            }

            return false;
        }

        private static string Normalize(string value)
        {
            return new string((value ?? string.Empty)
                .Where(char.IsLetterOrDigit)
                .ToArray())
                .ToLowerInvariant();
        }
    }
}